apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30033
      targetPort: 80
      protocol: TCP
  selector:
    app: web-ui
    function: frontend
